version: 0.2
phases:
  install:
    commands:
      - sam package --template-file sample.yaml --s3-bucket coms6998hw2-b2 --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
    - sample.yaml
