AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An Amazon S3 trigger that retrieves metadata for the object that has been
  updated.
Resources:
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./index-photos-copy
      Description: >-
        An Amazon S3 trigger that retrieves metadata for the object that has
        been updated.
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::359634618028:role/service-role/index-photos-role'
      Environment:
        Variables:
          REGION: us-east-1
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LFX2
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./search-photos-copy
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::359634618028:role/service-role/search-photos-role-uvdm8tzx'
      Environment:
        Variables:
          REGION: us-east-1
